// Doc: https://scalameta.org/scalafmt/docs/configuration.html
align.multiline = true
align.preset = true
lineEndings = unix
maxColumn = 100
newlines.source = fold
rewrite.rules = [SortImports]
runner.dialect = scala213
version = 3.10.7
