actions {
  check_cities {
    type = CustomDataFrameAction
    inputIds = [src_cities,tgt_region]
    mainInputId = src_cities
    outputIds = [error_cities]
    transformers = [{
      type = ScalaClassSparkDfsTransformer
      className = datamig.quality.QualityCitiesTransformer
    }]
    metadata.feed = check_data
  }
  load_cities {
    type = CustomDataFrameAction
    inputIds = [src_cities,tgt_region]
    mainInputId = src_cities
    outputIds = [tgt_cities]
    transformers = [{
      type = ScalaClassSparkDfsTransformer
      className = datamig.load.CitiesTransformer
    }]
    metadata.feed = load_data
  }
  load_country_region {
    type = CustomDataFrameAction
    inputIds = [src_country_region]
    mainInputId = src_country_region
    outputIds = [tgt_country,tgt_region]
    transformers = [{
      type = ScalaClassSparkDfsTransformer
      className = datamig.load.CountryRegionTransformer
      options = {
        // country-filter = ${global.environment.countryFilter}
      }
    }]
    metadata.feed = load_data
  }
}
