actions {
  check_cities {
    type = CustomDataFrameAction
    inputIds = [datamig_src_cities,datamig_tgt_region]
    mainInputId = datamig_src_cities
    outputIds = [error_cities]
    transformers = [{
      type = ScalaClassSparkDfsTransformer
      className = ch.datamig.quality.QualityCitiesTransformer
    }]
    metadata.feed = check_data
  }
  load_cities {
    type = CustomDataFrameAction
    inputIds = [datamig_src_cities,datamig_tgt_region]
    mainInputId = datamig_src_cities
    outputIds = [datamig_tgt_cities]
    transformers = [{
      type = ScalaClassSparkDfsTransformer
      className = ch.datamig.load.CitiesTransformer
    }]
    metadata.feed = load_data
  }
  load_country_region {
    type = CustomDataFrameAction
    inputIds = [datamig_src_country_region]
    mainInputId = datamig_src_country_region
    outputIds = [datamig_tgt_country,datamig_tgt_region]
    transformers = [{
      type = ScalaClassSparkDfsTransformer
      className = ch.datamig.load.CountryRegionTransformer
      options = {
        // country-filter = ${global.environment.countryFilter}
      }
    }]
    metadata.feed = load_data
  }
}
