actions {
  load_country_region {
    type = CustomDataFrameAction
    inputIds = [src_country_region]
    mainInputId = src_country_region
    outputIds = [tgt_country,tgt_region]
    transformers = [{
      type = ScalaClassSparkDfsTransformer
      className = datamig.load.CountryRegionTransformer
      options = {
        // country-filter = ${global.environment.countryFilter}
      }
    }]
    metadata.feed = load_country_region
  }
}
