connections {
  conn_source_db {
    type = JdbcTableConnection
    driver = ${?SOURCE_DRIVER}
    url = "jdbc:postgresql://"${?SOURCE_HOST}":"${?SOURCE_PORT}"/"${?SOURCE_DB}
    db = "\""${?SOURCE_DB}"\"" // need to quote in case of - in DBname
    authMode {
      type = BasicAuthMode
      userVariable = "ENV#SOURCE_USER"
      passwordVariable = "ENV#SOURCE_PW"
    }
  }
  conn_target_db {
    type = JdbcTableConnection
    driver = ${?TARGET_DRIVER}
    url = "jdbc:postgresql://"${?TARGET_HOST}":"${?TARGET_PORT}"/"${?TARGET_DB}
    db = "\""${?TARGET_DB}"\"" // need to quote in case of - in DBname
    authMode {
      type = BasicAuthMode
      userVariable = "ENV#TARGET_USER"
      passwordVariable = "ENV#TARGET_PW"
    }
  }
}

tgt.errortable.prefix = "datamig_tgt.error_"
