dataObjects {
  error_cities {
    type = JdbcTableDataObject
    connectionId = conn_target_db
    table {
      name = datamig_tgt.error_cities
    }
    schemaMin = "city STRING, city_ascii STRING, latitude REAL, longitude REAL, iso2 STRING, region_name STRING, population INTEGER, id INTEGER, reason STRING"
  }
}
