global {
  environment {
    dagGraphLogMaxLineLength = 512
    countryFilter = "iso_3166_1 = 'CH'"
  }
  sparkOptions {
    "spark.driver.maxResultSize" = 1g
    "spark.driver.memory" = 2g
    "spark.dynamicAllocation.enabled" = false
    "spark.executor.memory" = 8g
    "spark.memory.offHeap.enabled" = true
    "spark.memory.offHeap.size" = 8g
    "spark.network.timeout" = 3600s
    "spark.sql.caseSensitive" = false
    "spark.submit.deployMode" = client
  }
}
