dataObjects {
  src_country_region {
    type = JdbcTableDataObject
    connectionId = conn_target_db
    table {
      name = ${src.table.prefix}"country_region"
      primaryKey = [iso_3166_1,iso_3166_2]
    }
  }
}
