dataObjects {
  error_cities {
    type = JdbcTableDataObject
    connectionId = conn_target_db
    allowSchemaEvolution = false
    saveMode = Overwrite
    table {
      name = ${tgt.errortable.prefix}"cities"
      primaryKey = [id]
    }
  }

  tgt_cities {
    type = JdbcTableDataObject
    connectionId = conn_target_db
    saveMode = Overwrite
    table {
      name = ${tgt.table.prefix}"cities"
      primaryKey = [id]
    }
  }
  tgt_country {
    type = JdbcTableDataObject
    connectionId = conn_source_db
    saveMode = Overwrite
    table {
      name = ${tgt.table.prefix}"country"
      primaryKey = [iso_3166_1]
    }
  }
  tgt_region {
    type = JdbcTableDataObject
    connectionId = conn_source_db
    saveMode = Overwrite
    table {
      name = ${tgt.table.prefix}"region"
      primaryKey = [iso_3166_1,iso_3166_2]
    }
  }
}
